apiVersion: v1
kind: ConfigMap
metadata:
    name: grafana-datasource-tempo
    namespace: monitoring
    labels:
        grafana_datasource: "1"
data:
    datasource.yaml: |-
        apiVersion: 1
        datasources:
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo:3100
          jsonData:
            # For Service Graph, uses the default Prometheus datasource from kube-prometheus-stack
            serviceMap:
              datasourceUid: "prometheus"
